package com.example.myapplication.Workouts;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;

import androidx.fragment.app.Fragment;
import androidx.lifecycle.Observer;
import androidx.lifecycle.ViewModelProvider;
import androidx.navigation.Navigation;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import com.example.myapplication.Model.Shared.WorkoutModel;
import com.example.myapplication.R;

import java.util.ArrayList;
import java.util.List;


public class WorkoutsFragment extends Fragment {

    private WorkoutsViewModel viewModel;
    private List<WorkoutModel> workoutHistory = new ArrayList<>();
    private WorkoutAdapter adapter;

    public WorkoutsFragment() {
        // Autogenerated public constructor
    }

    public static WorkoutsFragment newInstance() {
        WorkoutsFragment fragment = new WorkoutsFragment();
        return fragment;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {

        // Inflate the layout for this fragment
        View view = inflater.inflate(R.layout.fragment_workouts, container, false);

        // Recyclerview
        RecyclerView recyclerView = view.findViewById(R.id.rv_workouts);
        recyclerView.setLayoutManager(new LinearLayoutManager(this.getContext()));
        recyclerView.hasFixedSize();

        adapter = new WorkoutAdapter(workoutHistory);
        recyclerView.setAdapter(adapter);

        // Initialise ViewModel and update adapter with LiveData
        viewModel = new ViewModelProvider(this).get(WorkoutsViewModel.class);
        viewModel.getWorkouts().observe(getViewLifecycleOwner(), new Observer<List<WorkoutModel>>() {
            @Override
            public void onChanged(List<WorkoutModel> workoutModels) {
                adapter.setWorkouts(workoutModels);
            }
        });

        // Setup navigation to new fragment via button
        Button logWorkoutButton = view.findViewById(R.id.log_new_button);
        logWorkoutButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Navigation.findNavController(view).navigate(R.id.action_workoutsFragment_to_workoutLogFragment);
            }
        });

        return view;
    }


}