package com.example.myapplication.Workouts;

import android.os.Bundle;
import android.text.TextUtils;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CalendarView;
import android.widget.EditText;
import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.fragment.app.Fragment;
import androidx.lifecycle.ViewModelProvider;
import androidx.navigation.Navigation;

import com.example.myapplication.R;

import java.util.Date;


public class WorkoutLogFragment extends Fragment {

    private WorkoutsViewModel viewModel;
    private long calendarDate;

    public WorkoutLogFragment() {
        // Autogenerated public constructor
    }

    public static WorkoutLogFragment newInstance() {
        WorkoutLogFragment fragment = new WorkoutLogFragment();
        return fragment;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {

        // Inflate the layout for this fragment
        View view = inflater.inflate(R.layout.fragment_workout_log, container, false);

        // Initialise ViewModel
        viewModel = new ViewModelProvider(this).get(WorkoutsViewModel.class);

        // TextFields
        EditText muscleGroupField = view.findViewById(R.id.editTextMuscleGroup);
        EditText descriptionField = view.findViewById(R.id.editTextDescription);

        // CalendarView
        CalendarView calendar = view.findViewById(R.id.calendarView);
        calendarDate = calendar.getDate();
        calendar.setOnDateChangeListener(new CalendarView.OnDateChangeListener() {
            @Override
            public void onSelectedDayChange(@NonNull CalendarView view, int year, int month, int dayOfMonth) {
                Date _tmp = new Date(year - 1900, month, dayOfMonth);
                calendarDate = _tmp.getTime();
            }
        });


        // Log button
        Button logButton = view.findViewById(R.id.button_log);

        logButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if ((!TextUtils.isEmpty(muscleGroupField.getText().toString())) && (!TextUtils.isEmpty(descriptionField.getText().toString()))) {
                    viewModel.addWorkout(descriptionField.getText().toString(), muscleGroupField.getText().toString(), new Date(calendarDate));
                    Toast.makeText(getContext(), "Workout logged!", Toast.LENGTH_LONG).show();
                }
                else {
                    Toast.makeText(getContext(), "All fields must be specified to log new workout", Toast.LENGTH_LONG).show();
                }
            }
        });

        // Back button
        Button backButton = view.findViewById(R.id.button_back);
        backButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Navigation.findNavController(view).navigate(R.id.action_workoutLogFragment_to_workoutsFragment);
            }
        });

        return view;
    }
}