package com.example.myapplication.Exercises;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;

import androidx.fragment.app.Fragment;

import com.example.myapplication.R;


public class ExerciseDetailFragment extends Fragment {


    public ExerciseDetailFragment() {
        // Autogenerated public constructor
    }

    public static ExerciseDetailFragment newInstance() {
        ExerciseDetailFragment fragment = new ExerciseDetailFragment();
        return fragment;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {

        // Inflate the layout for this fragment
        View view = inflater.inflate(R.layout.fragment_exercise_detail, container, false);

        // Name TextView
        TextView name_tv = view.findViewById(R.id.tv_name);
        name_tv.setText(getArguments().getString("name"));

        // Description TextView
        TextView description_tv = view.findViewById(R.id.tv_description);
        description_tv.setText(getArguments().getString("description"));

        return view;
    }
}