package com.example.myapplication.Exercises;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import androidx.fragment.app.Fragment;
import androidx.lifecycle.Observer;
import androidx.lifecycle.ViewModelProvider;
import androidx.navigation.Navigation;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import com.example.myapplication.Model.RetroFit.ExerciseResponse;
import com.example.myapplication.R;

import java.util.ArrayList;
import java.util.List;


public class ExercisesFragment extends Fragment implements OnListItemClickListener {

    private ExercisesViewModel viewModel;
    private ExerciseAdapter adapter;
    private List<ExerciseResponse.Result> exercisesList = new ArrayList<>();

    public ExercisesFragment() {
        // Autogenerated public constructor
    }

    public static ExercisesFragment newInstance() {
        ExercisesFragment fragment = new ExercisesFragment();
        return fragment;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        View view = inflater.inflate(R.layout.fragment_exercises, container, false);

        // Recyclerview
        RecyclerView recyclerView = view.findViewById(R.id.exercises_rv);
        recyclerView.setLayoutManager(new LinearLayoutManager(this.getContext()));
        recyclerView.hasFixedSize();

        adapter = new ExerciseAdapter(exercisesList, this);
        recyclerView.setAdapter(adapter);

        // Initialise ViewModel and update adapter with LiveData
        viewModel = new ViewModelProvider(this).get(ExercisesViewModel.class);
        viewModel.getExercises().observe(getViewLifecycleOwner(), new Observer<List<ExerciseResponse.Result>>() {
            @Override
            public void onChanged(List<ExerciseResponse.Result> exercises) {
                adapter.setExercises(exercises);
                exercisesList = exercises;
            }
        });

        return view;
    }

    @Override
    public void onListItemClick(int itemIndex) {

        Bundle bundle = new Bundle();
        bundle.putString("name", exercisesList.get(itemIndex).name);
        bundle.putString("description", exercisesList.get(itemIndex).description);

        Navigation.findNavController(getView()).navigate(R.id.action_exercisesFragment_to_exerciseDetailFragment, bundle);
    }
}